### ISSUE TITLE
Installation fails on Ampere servers (RTX A6000)

### ISSUE THREAD

**Issue by UtkrishtP** [initzhang/dc_dgl#4]
## ❓ Questions and Help

Here are our environment details:

```
$ pip freeze
certifi==2024.2.2
charset-normalizer==3.3.2
dgl==0.9
idna==3.6
importlib_metadata==7.1.0
mkl-fft @ file:///croot/mkl_fft_1695058164594/work
mkl-random @ file:///croot/mkl_random_1695059800811/work
mkl-service==2.4.0
networkx==3.0
numpy @ file:///croot/numpy_and_numpy_base_1708638617955/work/dist/numpy-1.26.4-cp39-cp39-linux_x86_64.whl#sha256=6094eeedd869502faa0fd0a8c5ad3a70c5779be06ddd1feb7627e5c212fac420
Pillow==9.3.0
psutil==5.9.8
requests==2.31.0
scipy==1.13.0
torch==1.9.1
torchaudio==0.9.0a0+a85b239
torchvision==0.10.1
tqdm==4.66.2
typing_extensions @ file:///croot/typing_extensions_1705599297034/work
urllib3==2.2.1
zipp==3.18.1

$ python -V
Python 3.9.19


```

The installation gets indefinitely stuck on this:
```
dc_dgl$ python test_installation.py                                                                                         
==================                                                                                                                                                      
test installation                                                                                                                                                       
/data2/miniconda3/envs/ducati_yash/lib/python3.9/site-packages/torch/cuda/__init__.py:106: UserWarning:                                                                 
NVIDIA RTX A6000 with CUDA capability sm_86 is not compatible with the current PyTorch installation.                                                                    
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.                                 
```

Is there any way to work with latest pytorch version to compile the above? 

We tried installing it with latest torch, but there was some error during make, seems not to have backward compatibility with current DGL codebase, will update the error details here

Let us know if you need any other details meanwhile?

**Comment by UtkrishtP** [comment]
Installation issue with CUDA-12.1, gcc-11:

```
In file included from /media/utkrisht/miniconda3/envs/ducati_amp/lib/python3.11/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,                     
                 from /media/utkrisht/dc_dgl/tensoradapter/pytorch/torch.cpp:8:
/media/utkrisht/miniconda3/envs/ducati_amp/lib/python3.11/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4:2: error: #error C++17 or later compatible compiler is required to use PyTorch.
    4 | #error C++17 or later compatible compiler is required to use PyTorch.
      |  ^~~~~
In file included from /media/utkrisht/miniconda3/envs/ducati_amp/lib/python3.11/site-packages/torch/include/c10/util/TypeList.h:3,
                 from /media/utkrisht/miniconda3/envs/ducati_amp/lib/python3.11/site-packages/torch/include/c10/util/Metaprogramming.h:3,
                 from /media/utkrisht/miniconda3/envs/ducati_amp/lib/python3.11/site-packages/torch/include/c10/core/DispatchKeySet.h:4,
                 from /media/utkrisht/miniconda3/envs/ducati_amp/lib/python3.11/site-packages/torch/include/c10/core/Backend.h:5,
                 from /media/utkrisht/miniconda3/envs/ducati_amp/lib/python3.11/site-packages/torch/include/c10/core/Layout.h:3,
                 from /media/utkrisht/miniconda3/envs/ducati_amp/lib/python3.11/site-packages/torch/include/ATen/core/TensorBody.h:12,
                 from /media/utkrisht/miniconda3/envs/ducati_amp/lib/python3.11/site-packages/torch/include/ATen/core/Tensor.h:3,
                 from /media/utkrisht/miniconda3/envs/ducati_amp/lib/python3.11/site-packages/torch/include/ATen/Tensor.h:3,
                 from /media/utkrisht/miniconda3/envs/ducati_amp/lib/python3.11/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /media/utkrisht/miniconda3/envs/ducati_amp/lib/python3.11/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /media/utkrisht/miniconda3/envs/ducati_amp/lib/python3.11/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /media/utkrisht/miniconda3/envs/ducati_amp/lib/python3.11/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /media/utkrisht/miniconda3/envs/ducati_amp/lib/python3.11/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /media/utkrisht/miniconda3/envs/ducati_amp/lib/python3.11/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /media/utkrisht/miniconda3/envs/ducati_amp/lib/python3.11/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /media/utkrisht/dc_dgl/tensoradapter/pytorch/torch.cpp:8:
/media/utkrisht/miniconda3/envs/ducati_amp/lib/python3.11/site-packages/torch/include/c10/util/C++17.h:27:2: error: #error You need C++17 to compile PyTorch
   27 | #error You need C++17 to compile PyTorch
      |  ^~~~~
```

Have attached the cmake output below:
```
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-11 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Start configuring project dgl
-- Build with CUDA support
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-12.1/ (found version "12.1") 
-- Found CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-12.1/
-- Found CUDA_CUDART_LIBRARY=/usr/local/cuda-12.1/lib64/libcudart.so
-- Found CUDA_CUBLAS_LIBRARY=/usr/local/cuda-12.1/lib64/libcublas.so
-- Found CUDA_CURAND_LIBRARY=/usr/local/cuda-12.1/lib64/libcurand.so
CMake Warning at cmake/modules/CUDA.cmake:71 (message):
  Running GPU detection script with nvcc failed:
Call Stack (most recent call first):
  cmake/modules/CUDA.cmake:132 (dgl_detect_installed_gpus)
  cmake/modules/CUDA.cmake:266 (dgl_select_nvcc_arch_flags)
  CMakeLists.txt:185 (dgl_config_cuda)


CMake Warning at cmake/modules/CUDA.cmake:76 (message):
  Automatic GPU detection failed.  Building for all known architectures (35
  50 60 70 80).
Call Stack (most recent call first):
  cmake/modules/CUDA.cmake:132 (dgl_detect_installed_gpus)
  cmake/modules/CUDA.cmake:266 (dgl_select_nvcc_arch_flags)
  CMakeLists.txt:185 (dgl_config_cuda)

-- Performing Test SUPPORT_CXX14
-- Performing Test SUPPORT_CXX14 - Success
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Build with OpenMP.
-- Build with LIBXSMM optimization.
-- -fopenmp -O2 -Wall -Wno-error=sign-compare -fPIC -std=c++17  -DUSE_AVX -DUSE_LIBXSMM -DDGL_CPU_LLC_SIZE=40000000 -DIDXTYPEWIDTH=64 -DREALTYPEWIDTH=32
-- Running GPU architecture autodetection
-- CUDA flags: -std=c++17;-Xcompiler ,-fopenmp,-O2,-Wall,-Wno-error=sign-compare,-fPIC,-std=c++17,,-DUSE_AVX,-DUSE_LIBXSMM,-DDGL_CPU_LLC_SIZE=40000000,-DIDXTYPEWIDTH=64,-DREALTYPEWIDTH=32;--expt-relaxed-constexpr;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_80,code=sm_80;--expt-extended-lambda;-Wno-deprecated-declarations;-std=c++17
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for fopen64
-- Looking for fopen64 - not found
-- Looking for C++ include cxxabi.h
-- Looking for C++ include cxxabi.h - found
-- Looking for nanosleep
-- Looking for nanosleep - found
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /usr/include  
-- /media/utkrisht/ducati_amp/dc_dgl/third_party/dmlc-core/cmake/build_config.h.in -> include/dmlc/build_config.h
-- Performing Test SUPPORT_MSSE2
-- Performing Test SUPPORT_MSSE2 - Success
-- Looking for execinfo.h
-- Looking for execinfo.h - found
-- Looking for getline
-- Looking for getline - found
-- Performing Test UV_LINT_W4
-- Performing Test UV_LINT_W4 - Failed
-- Performing Test UV_LINT_NO_UNUSED_PARAMETER_MSVC
-- Performing Test UV_LINT_NO_UNUSED_PARAMETER_MSVC - Failed
-- Performing Test UV_LINT_NO_CONDITIONAL_CONSTANT_MSVC
-- Performing Test UV_LINT_NO_CONDITIONAL_CONSTANT_MSVC - Failed
-- Performing Test UV_LINT_NO_NONSTANDARD_MSVC
-- Performing Test UV_LINT_NO_NONSTANDARD_MSVC - Failed
-- Performing Test UV_LINT_NO_NONSTANDARD_EMPTY_TU_MSVC
-- Performing Test UV_LINT_NO_NONSTANDARD_EMPTY_TU_MSVC - Failed
-- Performing Test UV_LINT_NO_NONSTANDARD_FILE_SCOPE_MSVC
-- Performing Test UV_LINT_NO_NONSTANDARD_FILE_SCOPE_MSVC - Failed
-- Performing Test UV_LINT_NO_NONSTANDARD_NONSTATIC_DLIMPORT_MSVC
-- Performing Test UV_LINT_NO_NONSTANDARD_NONSTATIC_DLIMPORT_MSVC - Failed
-- Performing Test UV_LINT_NO_HIDES_LOCAL
-- Performing Test UV_LINT_NO_HIDES_LOCAL - Failed
-- Performing Test UV_LINT_NO_HIDES_PARAM
-- Performing Test UV_LINT_NO_HIDES_PARAM - Failed
-- Performing Test UV_LINT_NO_HIDES_GLOBAL
-- Performing Test UV_LINT_NO_HIDES_GLOBAL - Failed
-- Performing Test UV_LINT_NO_CONDITIONAL_ASSIGNMENT_MSVC
-- Performing Test UV_LINT_NO_CONDITIONAL_ASSIGNMENT_MSVC - Failed
-- Performing Test UV_LINT_NO_UNSAFE_MSVC
-- Performing Test UV_LINT_NO_UNSAFE_MSVC - Failed
-- Performing Test UV_LINT_WALL
-- Performing Test UV_LINT_WALL - Success
-- Performing Test UV_LINT_NO_UNUSED_PARAMETER
-- Performing Test UV_LINT_NO_UNUSED_PARAMETER - Success
-- Performing Test UV_LINT_STRICT_PROTOTYPES
-- Performing Test UV_LINT_STRICT_PROTOTYPES - Success
-- Performing Test UV_LINT_EXTRA
-- Performing Test UV_LINT_EXTRA - Success
-- Performing Test UV_LINT_UTF8_MSVC
-- Performing Test UV_LINT_UTF8_MSVC - Failed
-- Performing Test UV_F_STRICT_ALIASING
-- Performing Test UV_F_STRICT_ALIASING - Success
-- summary of build options:
    Install prefix:  /usr/local
    Target system:   Linux
    Compiler:
      C compiler:    /usr/bin/cc
      CFLAGS:         -fopenmp -O2  -Wno-error=sign-compare -fPIC  -DUSE_AVX -DUSE_LIBXSMM -DDGL_CPU_LLC_SIZE=40000000 -DIDXTYPEWIDTH=64 -DREALTYPEWIDTH=32 -DLINUX -D_FILE_OFFSET_BITS=64 -std=c99 -fno-strict-aliasing -march=native -fPIC -Werror   -Wno-unused-function -Wno-unused-but-set-variable -Wno-unused-variable -Wno-unknown-pragmas -DNDEBUG -DNDEBUG2 -DHAVE_EXECINFO_H -DHAVE_GETLINE -O3 -Wno-error=sign-compare

-- Found uv: 1.38.1 (found version "1.38.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /media/utkrisht/ducati_amp/dc_dgl/build

```

**Comment by initzhang** [comment]
Hi @UtkrishtP , I have no access to A6000, but I have successfully build dc_dgl with A30, which is also an Ampere GPU. Below gives key points:

1. Build with `torch-1.13.1+cu117`. CUDA≥11 is required for Ampere GPU. But CUDA 12 is not compatible with dgl v0.8 codebase. (actually, use sm_80 instead of sm_35 in [this line of code](https://github.com/initzhang/dc_dgl/blob/a80379e5bfbd95d3d8d34f0472d372e8b01fcf7b/cmake/modules/CUDA.cmake#L57) can solve your cmake error above, but I haven't check further if there are any other problems)
2. Build with `gcc9`. gcc11 causes some deadlocks during building on my machine, haven't investigated why.

Please let me know if this help.

**Comment by UtkrishtP** [comment]
Hey,
Thanks for reverting back.

I have resolved the issue for now.
Used the following config:

```
Python = 3.9.4

Cuda 11.1

pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html

Gcc-7
G++-7

conda install cudnn==7.6.5 -c pytorch

```

The repo is set and running with Ampere machines
